# Generated by Django 3.1.5 on 2021-01-31 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_drone_manufacturing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='drone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drone', to='drones.drone'),
        ),
    ]
