# Generated by Django 3.1.5 on 2021-01-29 18:04

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='user.png', upload_to=apps.authentication.models.upload_to, verbose_name='Avatar'),
        ),
    ]
